### ISSUE TITLE
ohai plugin error

### ISSUE THREAD

**Issue by luizgamabh** [zanui/chef-thumbor#17]
There's some error with nginx ohai implementation on Ubuntu 14.04.4 (ubuntu/trusty64)

```
==> default: NoMethodError
...
==> default: undefined method `[]' for nil:NilClass
...
==> default:  27>> template "#{node['ohai']['plugin_path']}/nginx.rb" do
```

Update:

**I think just changing nginx cookbook dependency version to >= 2.7.6 solves the problem, because it updated ohai recipe to work with v4.2.0 of the ohai cookbook**

else just lock dependencies working major versions instead of **>= 0.0.0**.
